version: 2.1

jobs:
  prepare-node:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run:
        - cd ~/project/themes/default
        - npm i
        - npm run build

workflows:
  prepare:
    jobs:
      - prepare-node
