version: 2.1

jobs:
  prepare-node:
    docker:
      - image: circleci/node:12.2.0
    working_directory: ~/project/themes/default
    steps:
      - checkout
      - run: npm i
      - run: npm run build

workflows:
  prepare:
    jobs:
      - prepare-node
