version: 2.1

jobs:
  prepare-node:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "~/project/themes/default/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          working_directory: ~/project/themes/default
          command: |
            npm i
            npm build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "~/project/themes/default/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  prepare-lein:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run: lein deps
      -  save_cache:
           paths:
             - ~/.m2
           key: deps-{{ checksum "project.clj" }}


workflows:
  prepare:
    jobs:
      - prepare-node:
          filters:
            branches:
              only: develop
      - prepare-lein:
          requires:
            - prepare-node
          filters:
            branches:
              only: develop
