version: 2.1

jobs:
  prepare-node:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "~/project/themes/default/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          working_directory: ~/project/themes/default
          command: |
            npm i
            npm build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "~/project/themes/default/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  prepare-lein:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run: lein deps
      -  save_cache:
           paths:
             - ~/.m2
           key: deps-{{ checksum "project.clj" }}

  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run:
          working_directory: ~
          command: |
            curl -L --output ~/sass.tar.gz https://github.com/sass/dart-sass/releases/download/1.25.0/dart-sass-1.25.0-linux-x64.tar.gz
            tar -xzvf ~/sass.tar.gz
            echo 'export PATH=~/dart-sass:$PATH' >> $BASH_ENV
            source ~/.bashrc
      - run: lein run
      - persist_to_workspace:
          root: ~/project/public
          paths:
            - .

workflows:
  prepare:
    jobs:
      - prepare-node:
          filters:
            branches:
              only: develop
      - prepare-lein:
          requires:
            - prepare-node
          filters:
            branches:
              only: develop
      - build:
          requires:
            - prepare-lein
          filters:
            branches:
              only: develop
